import 'dotenv/config'

export const host = process.env.HOST ?? ''
export const mailerHost = process.env.MAILERHOST ?? ''
export const mailerPort = process.env.MAILERPORT ?? ''
export const mailerSecure = process.env.MAILERSECURE ?? ''
export const user = process.env.DATABASEUSER ?? ''
export const database = process.env.DATABASE ?? ''
export const password = process.env.PASSWORD ?? ''
export const secret = process.env.JWT_SECRET ?? ''
export const expires = process.env.JWT_EXPIRES_IN ?? ''
export const apiUrl = process.env.API_URL ?? ''
export const mailerEmail = process.env.MAILEREMAIL ?? ''
export const mailerPassword = process.env.MAILERPASSWORD ?? ''
export const webUrl = process.env.WEB_URL ?? ''
export const refreshSecret = process.env.JWT_REFRESH_SECRET ?? ''
export const refreshExpired = process.env.JWT_REFRESH_EXPIRED ?? ''
